.PHONY: all run
bstree:
	g++ -o a.exe BSTreeMain.cpp -std=c++17
rbtree:
	g++ -o a.exe RBTreeMain.cpp -std=c++17
	./a.exe
avl: 
	g++ -o a.exe AVLTreeMain.cpp -std=c++17
	./a.exe
test:
	g++ -o a.exe test.cpp -std=c++17
	./a.exe
run: all
	./a.exe